import { HexEditorTheme } from '.';

const hexEditorTheme: HexEditorTheme = {
  asciiPaddingX: 0,
  bytePaddingX: '0.1em',
  rowPaddingY: '0.1em',
  colorBackground: '#282c34',
  colorBackgroundEven: '#282c34',
  colorBackgroundCursor: '#5c6370',
  colorBackgroundCursorHighlight: '#7f848e',
  colorBackgroundColumnEven: '#282c34',
  colorBackgroundColumnOdd: '#181a1f',
  colorBackgroundInactiveCursor: '#5c6370',
  colorBackgroundInactiveCursorHighlight: '#5c6370',
  colorBackgroundInactiveSelection: '#5c6370',
  colorBackgroundInactiveSelectionCursor: '#5c6370',
  colorBackgroundLabel: '#282c34',
  colorBackgroundLabelCurrent: '#282c34',
  colorBackgroundOdd: '#181a1f',
  colorBackgroundRowEven: '#282c34',
  colorBackgroundRowOdd: '#181a1f',
  colorBackgroundSelection: '#589bd3',
  colorBackgroundSelectionCursor: '#61afef',
  colorScrollbackTrack: '#282c34',
  colorScrollbackThumb: '#495162',
  colorScrollbackThumbHover: '#5c6370',
  colorText: '#abb2bf',
  colorTextEven: '#abb2bf',
  colorTextCursor: '#f8fafd',
  colorTextCursorHighlight: '#ffffff',
  colorTextColumnEven: '#abb2bf',
  colorTextColumnOdd: '#abb2bf',
  colorTextInactiveCursor: '#abb2bf',
  colorTextInactiveCursorHighlight: '#abb2bf',
  colorTextInactiveSelection: '#56b6c2',
  colorTextInactiveSelectionCursor: '#56b6c2',
  colorTextLabel: '#495162',
  colorTextLabelCurrent: '#737984',
  colorTextOdd: '#abb2bf',
  colorTextRowEven: '#abb2bf',
  colorTextRowOdd: '#abb2bf',
  colorTextSelection: '#d7dae0',
  colorTextSelectionCursor: '#ffffff',
  fontFamily: 'monospace',
  fontSize: '16px',
  gutterWidth: '0.5em',
  cursorBlinkSpeed: '0.5s',
  labelPaddingX: '0.5em',
  scrollWidth: 'auto',
  textTransform: 'uppercase',
};

export default hexEditorTheme;